# .cargo/config.toml

[env]
FFMPEG_DOWNLOAD_BUILD = "1"
FFMPEG_STATIC = "1"
FFMPEG_VERSION = "7.1.1"

# Disable problematic docs generation
FFMPEG_DISABLE_DOC = "1"

# Extra configure flags passed to ffmpeg build
FFMPEG_CONFIGURE_FLAGS = "--disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages"