/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioMetadata {
  title?: string
  artist?: string
  album?: string
  genre?: string
  year?: number
  duration: number
  bitrate: number
  sampleRate: number
  channels: number
  format: string
}
export function analyzeAudio(path: string): AudioMetadata
export function generateWaveform(path: string): Array<number>
