/* tslint:disable */

/* auto-generated by NAPI-RS — server-side type declarations */

export interface AudioMetadata {
  title?: string
  artist?: string
  album?: string
  genre?: string
  year?: number
  duration: number
  bitrate: number
  sampleRate: number
  channels: number
  format: string
  loudness?: number
  bpm?: number
  key?: string
  scale?: string
  camelotKey?: string
  bpmConfidence?: number
  energy?: number
  danceability?: number
}

export interface SubtitleTrackInfo {
  index: number
  codec: string
  language?: string
  title?: string
}

export interface AudioAnalysis {
  bpm: number
  key: string
  camelotKey: string
  energy: number
  loudness: number
}

export interface ReplayGainResult {
  trackGain: number
  trackPeak: number
}

export interface SubtitleTrack {
  index: number
  codecName: string
  language?: string
  title?: string
}

export interface TagInput {
  title?: string
  artist?: string
  album?: string
  albumArtist?: string
  year?: number
  genre?: string
  trackNumber?: number
  discNumber?: number
}

export interface HardwareCodecSupport {
  h264: boolean
  hevc: boolean
  av1: boolean
  vp9: boolean
}

export interface TrackMetadata {
  // ── tags ──────────────────────────────────────────────────────────────
  title?: string
  artist?: string
  albumArtist?: string
  album?: string
  year?: number
  genre?: string
  trackNumber?: number
  discNumber?: number
  composer?: string
  lyricist?: string
  comment?: string
  copyright?: string
  encoder?: string
  lyrics?: string
  syncedLyrics?: string

  // ── stream info ────────────────────────────────────────────────────────
  duration: number
  sampleRate?: number
  bitRate?: number
  channels?: number
  /** Primary audio codec name (e.g. "aac", "mp3") */
  codecName?: string
  /** "audio" | "video" */
  fileType: string

  // ── video-specific ─────────────────────────────────────────────────────
  width?: number
  height?: number
  frameRate?: number
  videoCodec?: string
  audioCodec?: string

  // ── cover art ──────────────────────────────────────────────────────────
  coverArtBytes?: Array<number>
  dominantColor?: string

  // ── ReplayGain tags ────────────────────────────────────────────────────
  replaygainTrackGain?: number
  replaygainAlbumGain?: number
  replaygainTrackPeak?: number
  replaygainAlbumPeak?: number
}

export interface FingerprintResult {
  fingerprint: string
  duration: number
}

export interface ScannedFile {
  path: string
  mtime: number
  size: number
}

export declare function extractMetadata(path: string): TrackMetadata
export declare function generateThumbnail(path: string, timeSeconds: number, outputPath: string): void
export declare function getSubtitleTracks(path: string): Array<SubtitleTrack>
export declare function writeTags(path: string, tags: TagInput): void
export declare function probeHardwareCodecs(): HardwareCodecSupport
export declare function extractSubtitleStream(path: string, streamIndex: number): string
export declare function analyzeAudio(path: string): AudioAnalysis
export declare function computeReplayGain(paths: Array<string>): Array<ReplayGainResult>
export declare function generateWaveform(path: string): Array<number>
export declare function generateWaveformFingerprint(path: string): string
export declare function generateFingerprint(path: string): FingerprintResult
export declare function scanFolders(folders: Array<string>): Array<ScannedFile>